# Site Info
title: Data Science
tagline: 'by museonghwang'
description: 'Computer Vision is everything'
url: https://museonghwang.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: museonghwang
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar: 2b77edad331dac5458db5e37872042a7 # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/museonghwang
    
    # facebook:  <hide>
    #twitter:   https://twitter.com/Li_Zhihao
    #weibo:     http://weibo.com/41173780
    #email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=
    #instagram :   https://instagram.com/yngie_daily

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/otaru.jpg
  caption: Otaru, Japan

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

